# Generated by Django 3.2.25 on 2026-01-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=20)),
                ('applicant_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PROCESSING', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
